# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {

  "sphinx-panels" = super.buildPythonPackage rec {
    pname = "sphinx-panels";
    version = "0.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6b/2e/d1c2f2095bffe0830017a07c7047db357cc0ae31d770e70c4ec6802fd4e1/sphinx_panels-0.5.2-py3-none-any.whl";
      sha256 = "1wfjc694xqs6n78sgviap6pfg0irmawxziyn6aifg504id21hbib";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."sphinx"
    ];
  };

  "sphinx-thebe" = super.buildPythonPackage rec {
    pname = "sphinx-thebe";
    version = "0.0.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/63/8bb9712f7fc07e1ea9e8c4bb9458e11e9e4698bef95c74976e10b382d04d/sphinx_thebe-0.0.8-py3-none-any.whl";
      sha256 = "1368pxbbfgrm6a1ah3mkw6w792hhhji8kv0lbffm626kcvmgcg6x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sphinx"
    ];
  };

  "jupytext" = super.buildPythonPackage rec {
    pname = "jupytext";
    version = "1.10.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/d0/aeba0c91e3eb7331c4364f2f77198d497c3187fa2eee294ed519cfa1650b/jupytext-1.10.3-py3-none-any.whl";
      sha256 = "1vd7y089rip3dnxkg8dkq9a1q61fl9ps0pgm90wq38ai04f3n4lb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markdown-it-py"
      self."nbformat"
      self."pyyaml"
      self."toml"
    ];
  };

  "markdown-it-py" = super.buildPythonPackage rec {
    pname = "markdown-it-py";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2e/cb/8493188845d26599170268bb0e0a63e75584d5e7f130488c641e96449cd7/markdown_it_py-0.6.2-py3-none-any.whl";
      sha256 = "1cdwcbwp9fmj23mpyx4apx1rmkan3p9kzdywy1fjmj4d37wfkcrh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."mdit-py-plugins"
    ];
  };

  "mdit-py-plugins" = super.buildPythonPackage rec {
    pname = "mdit-py-plugins";
    version = "0.2.8";
    src = super.fetchPypi {
      inherit pname version;
      sha256 = "sha256-WZHO9kVQLoClOI7E/CCIXSMT1Icei44yDKLeFKwMAV8=";
    };
    doCheck = false;
    postPatch = ''
      substituteInPlace setup.cfg --replace 'markdown-it-py~=1.0' ""
    '';
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
  };

  "sphinx-book-theme" = super.buildPythonPackage rec {
    pname = "sphinx-book-theme";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/f8/cf581c74d08c7578df552678ab9eeaafac0a6b31f7d041ce89369aeef2bb/sphinx_book_theme-0.1.0-py3-none-any.whl";
      sha256 = "1s9sblm9pbmjlsghgi74nc68nz31yci0jaq8yfl5gikn5qk5fbhq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."beautifulsoup4"
      self."click"
      self."docutils"
      self."pydata-sphinx-theme"
      self."pyyaml"
      self."sphinx"
    ];
  };

  "sphinx-multitoc-numbering" = super.buildPythonPackage rec {
    pname = "sphinx-multitoc-numbering";
    version = "0.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/9f/902f2030674cd9473fdbe5a2c2dec2618c27ec853484c35f82cf8df40ece/sphinx_multitoc_numbering-0.1.3-py3-none-any.whl";
      sha256 = "0545dp1484b5dh27817y0r8h4250b3k04hrxddisvf5jm43yglik";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sphinx"
    ];
  };

  sphinx-jupyterbook-latex = super.buildPythonPackage rec {
    pname = "sphinx-jupyterbook-latex";
    version = "0.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/f5/36102e7ee503ba8f4f59e769e058e354b164d2b6dcd2a502b3e354b10ef2/sphinx_jupyterbook_latex-0.4.2-py3-none-any.whl";
      sha256 = "151vx8rbcc4bms0klfplghlv2x1p21hb1lqbid8jbgdygx3bd2zq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-resources"
      self."sphinx"
    ];
  };

  "linkify-it-py" = super.buildPythonPackage rec {
    pname = "linkify-it-py";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/e8/839bad95b6ca684d18beba6dd9ff7b06a28778a57fd3fa6afbeb476e4be6/linkify_it_py-1.0.1-py3-none-any.whl";
      sha256 = "1z0xns16pbwnk40gjrhnw71zzjm785rpn5m8623r7zzh6r6h9fi9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."uc-micro-py"
    ];
  };

  "sphinx-togglebutton" = super.buildPythonPackage rec {
    pname = "sphinx-togglebutton";
    version = "0.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/42/deaa3b89f7617cee51df70c1bcecaf885ab3d59302a2b96ce89d85da118a/sphinx_togglebutton-0.2.3-py3-none-any.whl";
      sha256 = "1q6mp1v389xvfypraa2mz97x7q7fnx1ry64gj6kq0d0v9cahfdwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."setuptools"
      self."sphinx"
      self."wheel"
    ];
  };

  "sphinx-comments" = super.buildPythonPackage rec {
    pname = "sphinx-comments";
    version = "0.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/97/a5c39f619375d4f81d5422377fb027075898efa6b6202c1ccf1e5bb38a32/sphinx_comments-0.0.3-py3-none-any.whl";
      sha256 = "000xq8q2a9a3s1vm3699gk2my8i98sn42d1yz1ki8r7skd79p1qy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sphinx"
    ];
  };

  "myst-nb" = super.buildPythonPackage rec {
    pname = "myst-nb";
    version = "0.12.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/92/443573bf9dfdb078abc17fb167ddcb7f9fe6f20dac9348d8c2d814ceb221/myst_nb-0.12.3-py3-none-any.whl";
      sha256 = "1z83chs0n4b5gs9jvyc9fvmb8f9dr7zyjiw2kd0lh1vjjha1ki9v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."importlib-metadata"
      self."ipython"
      self."ipywidgets"
      self."jupyter-cache"
      self."jupyter-sphinx"
      self."myst-parser"
      self."nbconvert"
      self."nbformat"
      self."pyyaml"
      self."sphinx"
      self."sphinx-togglebutton"
    ];
  };

  "jupyter-cache" = super.buildPythonPackage rec {
    pname = "jupyter-cache";
    version = "0.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/b3/61010536aed0db73bf9bbc53e01dd6a60e9a5275e096bcd2f77f5c6db410/jupyter_cache-0.4.2-py3-none-any.whl";
      sha256 = "1zhhw06arxn6l1ag4k49dnm7bync049dna9s3apr5b457w6bl3nv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."nbclient"
      self."nbdime"
      self."nbformat"
      self."sqlalchemy"
    ];
  };

  "nbdime" = super.nbdime.overrideAttrs (old: {
    dontUsePytestCheck = true;
  });

  "myst-parser" = super.buildPythonPackage rec {
    pname = "myst-parser";
    version = "0.13.7";
    src = pkgs.fetchFromGitHub {
      owner = "executablebooks";
      repo = "MyST-Parser";
      rev = "v0.13.7";
      sha256 = "sha256-iBEPZG+Dmpcx1WHxWlJOjoctHuAw+J55asAbjmsvEos=";
    };
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."docutils"
      self."markdown-it-py"
      self."mdit-py-plugins"
      self."pyyaml"
      self."sphinx"
    ];
  };

  "nbconvert" = super.buildPythonPackage rec {
    pname = "nbconvert";
    version = "5.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/79/6c/05a569e9f703d18aacb89b7ad6075b404e8a4afde2c26b73ca77bb644b14/nbconvert-5.6.1-py2.py3-none-any.whl";
      sha256 = "1vpw4pvhv300rk61h143w7bl4325p3cizqhkm92xz5jzhw1yrmph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."pygments"
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jupyter_core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."testpath"
      self."traitlets"
    ];
  };

  "jupyter-sphinx" = super.buildPythonPackage rec {
    pname = "jupyter-sphinx";
    version = "0.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/39/71c0e8b0685381649df7916a661c50cd37200769892c5f1aab74bab1bbc1/jupyter_sphinx-0.3.2-py3-none-any.whl";
      sha256 = "1jbx422z7kzfnqm2lcw3r6cyp429q9h5pdpn09cbn1rhzg83c7ih";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."ipywidgets"
      self."nbconvert"
      self."nbformat"
      self."sphinx"
    ];
  };

  "sphinx-external-toc" = super.buildPythonPackage rec {
    pname = "sphinx-external-toc";
    version = "0.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/bf355e3c0262e70a00bfb9297b8eaaa773da029fec74552f43f36eb5be87/sphinx_external_toc-0.2.2-py3-none-any.whl";
      sha256 = "0857m8cl01bi7rwgx4z4ap9j0a9bqmgj92l36c48zgfgfhrsnfw5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."click"
      self."pyyaml"
      self."sphinx"
    ];
  };

  "pydata-sphinx-theme" = super.buildPythonPackage rec {
    pname = "pydata-sphinx-theme";
    version = "0.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/ea/9c007fdf60d05a201467724d88b2571edb356afb065edfb2a326670eab10/pydata_sphinx_theme-0.6.3-py3-none-any.whl";
      sha256 = "016vw3kvf5qxmla6nj61p7c3dlk0wy5kcmxyp6kfz99zqc6y5zph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."beautifulsoup4"
      self."docutils"
      self."sphinx"
    ];
  };

  "sphinx-copybutton" = super.buildPythonPackage rec {
    pname = "sphinx-copybutton";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/8b/7c9cf5956be80bfd826f2534e2b38ff2310f8c4274a77e4b3b2d846af552/sphinx_copybutton-0.4.0-py3-none-any.whl";
      sha256 = "1c681l9kpb7cildah0fx89m7iahj6hrq6b6f5pc6vb4x2qyd6h23";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sphinx"
    ];
  };

  "sphinx-tabs" = super.buildPythonPackage rec {
    pname = "sphinx-tabs";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/56/506dd97607b2f684612f5d927721141a4fdb644e353a300859b9fb81c39c/sphinx_tabs-3.1.0-py3-none-any.whl";
      sha256 = "0rwajmil0h28nx5if3aq396s2ma4qbzi78qrhicvhpn09gl99pv3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."pygments"
      self."sphinx"
    ];
  };

  "babel" = super.buildPythonPackage rec {
    pname = "babel";
    version = "2.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/96/4ba93c5f40459dc850d25f9ba93f869a623e77aaecc7a9344e19c01942cf/Babel-2.9.1-py2.py3-none-any.whl";
      sha256 = "1yfyn32hlv60sr0knymcb4msvd3slmcv4z5ny08wsdyrj4my2jdb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
  };

  "sphinxcontrib-htmlhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-htmlhelp";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/40/c854ef09500e25f6432dcbad0f37df87fd7046d376272292d8654cc71c95/sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl";
      sha256 = "01zdqq30si8yhvmy9w0v4idff4mc5pjs1v2r5gnf6ykrzcyj84nl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };

  "sphinxcontrib-serializinghtml" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-serializinghtml";
    version = "1.1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/77/5464ec50dd0f1c1037e3c93249b040c8fc8078fdda97530eeb02424b6eea/sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl";
      sha256 = "1zcjkfcjisxrgs3fk59zidzbbh2zkzbxgn7alz9p2i46mq09laim";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };

  "sphinx" = super.sphinx.overrideAttrs ( old: {
    version = "3.5.4";
  });

}
