# Book settings
title: Notes on (Baby)Pandas
author: Parker Addison and Justin Eldridge

html:
    use_repository_button: true
    use_issues_button: true
    home_page_in_navbar: false
    navbar_number_sections: true

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
    notebook_interface: classic
    jupyterhub_url: "https://datahub.ucsd.edu"

repository:
    url: https://github.com/dsc-courses/dsc10-notes
    path_to_book: . # link to the reader-friendly notebooks
    branch: notebooks

sphinx:
  extra_extensions:
  - sphinx_tabs.tabs
  - jupyterhublink
  - hiddenanswer
  - dterms
  - jupytertips
  - admonitionlists
