# Book settings
title: Dive into Data Science
author: Parker Addison and Justin Eldridge

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
  - sphinx_tabs.tabs
  - jupytertips
  - hiddenanswer
