on:
    push:
        branches:
            - main
jobs:
  build-html:
    runs-on: ubuntu-latest
    name: Build HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build HTML version of book
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop -c make html
      - uses: actions/upload-artifact@v2
        with:
            name: HTML
            path: book/_build/html/ # or path/to/artifact
      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: book/_build/html
