on:
    push:
        branches:
            - main
jobs:
  build-html:
    runs-on: self-hosted
    name: Build HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build HTML version of book
        run: nix develop --command make html
      - uses: actions/upload-artifact@v2
        with:
            name: HTML
            path: book/_build/html/ # or path/to/artifact
      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: book/_build/html
