name: Deploy

on:
    push:
        branches:
            - main
jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Course Notes
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: cachix/install-nix-action@v14.1
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build HTML Notes
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop -c make html

      - name: Deploy HTML Notes
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: src/_build/html

      - name: Build Clean Notebooks
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop -c make notebooks

      - name: Deploy Notebooks
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: notebooks
          FOLDER: _notebooks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

